name: Build and push container image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *" # as monthly build

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update devbox/status.txt
        run: |
          echo "Last updated: $(date -u)" > devbox/status.txt

      - name: Install QEMU dependency
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends \
          qemu-user-static

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            ./Containerfile

      - name: Push container image to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: docker.io
          image: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Apply automatic changes
        run: |
          git add -N .
          if ! git diff --exit-code --quiet; then
            git config --local user.name 'GitHub Actions'
            git config --local user.email 'actions@github.com'
            git add .
            git commit -m 'Apply automatic changes'
            git push
          fi
